-- ARQUIVO CONSOLIDADO DE INICIALIZAÇÃO COMPLETA (000_FULL_INITIAL_SETUP.sql)
-- Execute este script em um banco de dados VAZIO no Supabase para criar toda a estrutura necessária.

-- 1. Habilitar Extensões
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- 2. Estrutura Base (Legado/Existente do NB Admin)
-- Baseado no 007_clean_database_architecture.sql

-- Table: clientes_sistema
CREATE TABLE IF NOT EXISTS clientes_sistema (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    telefone VARCHAR(20),
    empresa VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: orcamentos_sistema
CREATE TABLE IF NOT EXISTS orcamentos_sistema (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    numero_orcamento VARCHAR(50) UNIQUE, -- Será preenchido por trigger
    cliente_id UUID REFERENCES clientes_sistema(id) ON DELETE CASCADE,
    usuario_id UUID, -- Link opcional para usuarios_sistema (auth)
    data_evento DATE,
    observacoes_cliente TEXT,
    status VARCHAR(20) DEFAULT 'pendente',
    valor_total DECIMAL(12,2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: ecologic_products (Catálogo)
-- Baseado no fix_ecologic_products_schema.sql
CREATE TABLE IF NOT EXISTS ecologic_products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo text NOT NULL,
    codigo text NOT NULL,
    titulo text,
    descricao text,
    img_0 text,
    img_1 text,
    img_2 text,
    categoria text,
    cor_web_principal text,
    altura numeric,
    largura numeric,
    comprimento numeric,
    peso numeric,
    variacoes jsonb
);

-- Table: itens_orcamento_sistema
CREATE TABLE IF NOT EXISTS itens_orcamento_sistema (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    orcamento_id UUID NOT NULL REFERENCES orcamentos_sistema(id) ON DELETE CASCADE,
    produto_ecologico_id BIGINT REFERENCES ecologic_products(id),
    quantidade INTEGER NOT NULL DEFAULT 1,
    observacoes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Table: usuarios_sistema (Para auth customizada se necessário)
CREATE TABLE IF NOT EXISTS usuarios_sistema (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID REFERENCES auth.users(id),
    nome TEXT,
    email TEXT,
    telefone TEXT,
    empresa TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- 3. Estrutura Unificada (Partners, Orders, Financeiro)
-- Baseado no 022_unified_schema.sql

-- Enum Partner Type
DO $$ BEGIN
    CREATE TYPE partner_type AS ENUM ('CLIENTE', 'FORNECEDOR', 'AMBOS');
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- Table: partners
CREATE TABLE IF NOT EXISTS partners (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  type partner_type NOT NULL DEFAULT 'CLIENTE',
  name text NOT NULL,
  doc text,
  email text, -- Unique constraint adicionada depois
  phone text,
  financial_email text,
  address_data jsonb DEFAULT '{}'::jsonb,
  company_name text,
  active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- Enum Order Status
DO $$ BEGIN
    CREATE TYPE order_status_type AS ENUM (
        'EM ABERTO', 'EM PRODUÇÃO', 'AGUARDANDO APROVAÇÃO', 
        'AGUARDANDO NF', 'AGUARDANDO PAGAMENTO', 
        'AGUARDANDO PERSONALIZAÇÃO', 'FINALIZADO', 'ENTRE FINALIZADO'
    );
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- Table: orders
CREATE TABLE IF NOT EXISTS orders (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  order_number text NOT NULL,
  quote_id uuid REFERENCES orcamentos_sistema(id),
  partner_id uuid REFERENCES partners(id),
  salesperson_id uuid REFERENCES auth.users(id),
  status order_status_type DEFAULT 'EM ABERTO',
  order_date date DEFAULT current_date,
  delivery_deadline date,
  total_amount numeric(10,2) DEFAULT 0,
  billing_type text,
  payment_method text,
  entry_amount numeric(10,2) DEFAULT 0,
  entry_date date,
  entry_confirmed boolean DEFAULT false,
  remaining_amount numeric(10,2) DEFAULT 0,
  remaining_date date,
  remaining_confirmed boolean DEFAULT false,
  invoice_number text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  UNIQUE(order_number)
);

-- Table: order_items
CREATE TABLE IF NOT EXISTS order_items (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  order_id uuid REFERENCES orders(id) ON DELETE CASCADE,
  product_id bigint,
  product_name text NOT NULL,
  supplier_id uuid REFERENCES partners(id),
  quantity integer DEFAULT 1,
  unit_price numeric(10,2) DEFAULT 0,
  total_item_value numeric(10,2) DEFAULT 0,
  cost_product numeric(10,2) DEFAULT 0,
  cost_customization numeric(10,2) DEFAULT 0,
  cost_freight numeric(10,2) DEFAULT 0,
  cost_extra numeric(10,2) DEFAULT 0,
  real_cost_product numeric(10,2) DEFAULT 0,
  real_cost_customization numeric(10,2) DEFAULT 0,
  real_cost_freight numeric(10,2) DEFAULT 0,
  real_cost_extra numeric(10,2) DEFAULT 0,
  is_paid_supplier boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now()
);

-- Table: commissions
CREATE TABLE IF NOT EXISTS commissions (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  order_id uuid REFERENCES orders(id) ON DELETE CASCADE,
  salesperson_id uuid REFERENCES auth.users(id),
  amount numeric(10,2) NOT NULL,
  type text NOT NULL,
  status text DEFAULT 'PENDING',
  percentage numeric(5,2) DEFAULT 3.00,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- Table: company_expenses
CREATE TABLE IF NOT EXISTS company_expenses (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  description text NOT NULL,
  amount numeric NOT NULL DEFAULT 0,
  due_date date NOT NULL,
  paid boolean DEFAULT false,
  paid_date date,
  category text,
  observation text,
  created_at timestamp with time zone DEFAULT now()
);

-- 4. Ajustes Finais e Colunas Extras (024)
-- Adicionar colunas de integração em ecologic_products
DO $$ BEGIN
    ALTER TABLE ecologic_products ADD COLUMN supplier_id uuid REFERENCES partners(id);
EXCEPTION WHEN duplicate_column THEN null; END $$;

DO $$ BEGIN
    ALTER TABLE ecologic_products ADD COLUMN cost_price numeric(10,2) DEFAULT 0;
EXCEPTION WHEN duplicate_column THEN null; END $$;

-- Adicionar colunas de snapshot em itens_orcamento_sistema
DO $$ BEGIN
    ALTER TABLE itens_orcamento_sistema ADD COLUMN unit_price numeric(10,2) DEFAULT 0;
EXCEPTION WHEN duplicate_column THEN null; END $$;

DO $$ BEGIN
    ALTER TABLE itens_orcamento_sistema ADD COLUMN total_price numeric(10,2) DEFAULT 0;
EXCEPTION WHEN duplicate_column THEN null; END $$;

-- 5. Funções Auxiliares

-- Update Updated At
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Triggers
DROP TRIGGER IF EXISTS update_clientes_sistema_updated_at ON clientes_sistema;
CREATE TRIGGER update_clientes_sistema_updated_at BEFORE UPDATE ON clientes_sistema FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_orcamentos_sistema_updated_at ON orcamentos_sistema;
CREATE TRIGGER update_orcamentos_sistema_updated_at BEFORE UPDATE ON orcamentos_sistema FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_partners_modtime ON partners;
CREATE TRIGGER update_partners_modtime BEFORE UPDATE ON partners FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

DROP TRIGGER IF EXISTS update_orders_modtime ON orders;
CREATE TRIGGER update_orders_modtime BEFORE UPDATE ON orders FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

-- Generate Quote Number (Simples)
CREATE OR REPLACE FUNCTION generate_quote_number()
RETURNS TEXT AS $$
DECLARE
    next_number INTEGER;
    quote_number TEXT;
BEGIN
    SELECT COALESCE(MAX(CAST(SUBSTRING(numero_orcamento FROM '[0-9]+$') AS INTEGER)), 0) + 1
    INTO next_number
    FROM orcamentos_sistema
    WHERE numero_orcamento ~ '^ORC-[0-9]+$';
    
    quote_number := 'ORC-' || LPAD(next_number::TEXT, 4, '0');
    RETURN quote_number;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION set_quote_number()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.numero_orcamento IS NULL OR NEW.numero_orcamento = '' THEN
        NEW.numero_orcamento := generate_quote_number();
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS set_orcamento_numero ON orcamentos_sistema;
CREATE TRIGGER set_orcamento_numero BEFORE INSERT ON orcamentos_sistema FOR EACH ROW EXECUTE FUNCTION set_quote_number();

-- 6. Função de Conversão (Quote -> Order)
CREATE OR REPLACE FUNCTION convert_quote_to_order(p_quote_id uuid, p_salesperson_id uuid DEFAULT auth.uid())
RETURNS uuid AS $$
DECLARE
  v_quote record;
  v_user record;
  v_partner_id uuid;
  v_order_id uuid;
  v_item record;
  v_product_name text;
BEGIN
  -- Get Quote
  SELECT * INTO v_quote FROM orcamentos_sistema WHERE id = p_quote_id;
  IF v_quote IS NULL THEN RAISE EXCEPTION 'Quote not found'; END IF;
  
  -- Get Client Info (Try to find in partners first by email from usuarios_sistema or clientes_sistema)
  -- Lógica simplificada: assume que clientes_sistema tem o email
  SELECT * INTO v_user FROM clientes_sistema WHERE id = v_quote.cliente_id;
  
  -- Find or Create Partner
  SELECT id INTO v_partner_id FROM partners WHERE email = v_user.email LIMIT 1;
  
  IF v_partner_id IS NULL THEN
    INSERT INTO partners (type, name, company_name, email, phone)
    VALUES ('CLIENTE', v_user.nome, v_user.empresa, v_user.email, v_user.telefone)
    RETURNING id INTO v_partner_id;
  END IF;
  
  -- Create Order
  INSERT INTO orders (
    order_number, quote_id, partner_id, salesperson_id, status, total_amount, created_at
  ) VALUES (
    v_quote.numero_orcamento, p_quote_id, v_partner_id, p_salesperson_id, 'EM ABERTO', v_quote.valor_total, now()
  ) RETURNING id INTO v_order_id;
  
  -- Migrate Items
  FOR v_item IN SELECT * FROM itens_orcamento_sistema WHERE orcamento_id = p_quote_id
  LOOP
    SELECT titulo INTO v_product_name FROM ecologic_products WHERE id = v_item.produto_ecologico_id;
    
    INSERT INTO order_items (
      order_id, product_id, product_name, quantity, unit_price, total_item_value
    ) VALUES (
      v_order_id, v_item.produto_ecologico_id, COALESCE(v_product_name, 'Produto ' || v_item.produto_ecologico_id),
      v_item.quantidade, v_item.unit_price, v_item.total_price
    );
  END LOOP;
  
  UPDATE orcamentos_sistema SET status = 'finalizado' WHERE id = p_quote_id;
  
  RETURN v_order_id;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 7. Habilitar RLS e Policies (Básico)
ALTER TABLE ecologic_products ENABLE ROW LEVEL SECURITY;
ALTER TABLE clientes_sistema ENABLE ROW LEVEL SECURITY;
ALTER TABLE orcamentos_sistema ENABLE ROW LEVEL SECURITY;
ALTER TABLE itens_orcamento_sistema ENABLE ROW LEVEL SECURITY;
ALTER TABLE partners ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

-- Políticas Permissivas para Desenvolvimento (Ajustar em Produção)
DO $$ 
DECLARE t text;
BEGIN 
  FOR t IN SELECT tablename FROM pg_tables WHERE schemaname = 'public' LOOP
    EXECUTE format('DROP POLICY IF EXISTS "Public Access %I" ON %I', t, t);
    EXECUTE format('CREATE POLICY "Public Access %I" ON %I FOR ALL USING (true)', t, t);
  END LOOP;
END $$;
