-- Migration 025: Create User Management Tables (Missing from initial setup)

-- 1. Create user_profiles table (Modern structure)
CREATE TABLE IF NOT EXISTS user_profiles (
  id uuid PRIMARY KEY DEFAULT uuid_generate_v4(),
  user_id uuid REFERENCES auth.users(id) ON DELETE CASCADE UNIQUE,
  full_name text,
  role text DEFAULT 'consultor', -- 'admin', 'consultor'
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- Enable RLS
ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;

-- Policies for user_profiles
DROP POLICY IF EXISTS "Public Access user_profiles" ON user_profiles;
CREATE POLICY "Public Access user_profiles" ON user_profiles FOR ALL USING (true); 
-- Note: In production, restrict to own user or admin


-- 2. Create consultores table (Legacy structure needed for frontend)
CREATE TABLE IF NOT EXISTS consultores (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_user_id uuid REFERENCES auth.users(id),
  nome text NOT NULL,
  email text UNIQUE NOT NULL,
  cpf text,
  telefone text,
  ativo boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

-- Enable RLS
ALTER TABLE consultores ENABLE ROW LEVEL SECURITY;

-- Policies for consultores
DROP POLICY IF EXISTS "Public Access consultores" ON consultores;
CREATE POLICY "Public Access consultores" ON consultores FOR ALL USING (true);


-- 3. Create configuracoes table (Also missing and needed for frontend settings)
CREATE TABLE IF NOT EXISTS configuracoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  chave text UNIQUE NOT NULL,
  valor text,
  categoria text,
  tipo text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now()
);

ALTER TABLE configuracoes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public Access configuracoes" ON configuracoes;
CREATE POLICY "Public Access configuracoes" ON configuracoes FOR ALL USING (true);
